### ISSUE TITLE
WebExtensions background script in the browser toolbox

### ISSUE THREAD

**Issue by clarkbw** [tromey/source-map-examples#1]
Here's the STR:

* `git clone https://github.com/rangle/augury.git` the https://github.com/rangle/augury Angular extension
* Follow Instructions
  * `cd augury`
  * `yarn`
  * `yarn run dev-build`
* Open `about:debugging` in Firefox Nightly
* Open the `augury` directory using the "Load Temporary Add-On" button
* Click the "debug" button

You should be seeing some webpack structure for the background.js script, but instead you get the build version only.

If you open up the normal devtools toolbox debugger you'll see the webpack we are expecting. (of course missing the background script because it is in a sandbox and not visible from this context)

**Comment by tromey** [comment]
The actor's form is
```
{"actor":"server2.conn0.child34/source29","generatedUrl":null,"url":"moz-extension://7d910910-ff94-4478-b3f4-94a6408c17b5/build/background.js","isBlackBoxed":false,"isPrettyPrinted":false,"isSourceMapped":false,"sourceMapURL":"background.js.map","introductionUrl":null,"introductionType":"scriptElement"}
```
So, that looks right.  I can't seem to get debugging logs out of the client side right now so it's hard to tell what's going wrong there.

**Comment by tromey** [comment]
Logging on the client also shows the correct source map url, so next up is finding out why the fetch fails.

**Comment by clarkbw** [comment]
I'm guessing `"isSourceMapped":false` is not a smoking gun... 😄

**Comment by tromey** [comment]
I think (not 100% sure) that's only set on actors for the original sources, so it wouldn't apply in this case, as we're not using the server-side source-mapping.

I seem to be seeing that the service is started with a threadClient not having a getSources method.  So something weird is going on there.  But, this shouldn't actually affect the debugger, either.  Even more bugs.

**Comment by clarkbw** [comment]
Thanks for looking into this!

**Comment by tromey** [comment]
I have a hypothesis now: the browser toolbox runs in a separate process, and if this process does not have the addon installed, then trying to fetch the source map via its `moz-extension://` URL will fail.  This would explain the errors like:
```
[22436] WARNING: NS_ENSURE_SUCCESS(rv, rv) failed with result 0x80040111: file /home/tromey/firefox-git/hg2/netwerk/protocol/res/SubstitutingProtocolHandler.cpp, line 251
```
(These come from the code implementing the `moz-extension` scheme.)
One thing undermining this idea, though, is that I also see failures like this from the main process.  I'm not sure what is going on there.  It's possible that there's some other problem in platform here, I'll look at that next.

**Comment by tromey** [comment]
I added some logging to `SubstitutingProtocolHandler::ResolveURI` and I see plenty of failing requests there (not coming from our code, and which I don't understand); and then also in the end our failing request.  Still not sure if the process theory is true.  My main question is how some requests end up with the `ExtensionProtocolHandler` and how others end up in `nsResProtocolHandler` or elsewhere.

**Comment by clarkbw** [comment]
> My main question is how some requests end up with the ExtensionProtocolHandler and how others end up in nsResProtocolHandler or elsewhere.

@rpl do you have any idea why this is true?

**Comment by rpl** [comment]
@clarkbw @tromey I've reproduced this issue locally and I'm digging into it a bit.

iirc the ExtensionProtocolHandler is a SubstitutingProtocolHandler subclass which turns the moz-extensions urls into the jar or file urls where the resource can be retrieved:

- http://searchfox.org/mozilla-central/rev/a83a4b68974aecaaacdf25145420e0fe97b7aa22/netwerk/protocol/res/ExtensionProtocolHandler.cpp#430,436

(e.g. jar urls when the extension is packed into an xpi, file urls when it is loaded temporarily from the about:debugging page by selecting the extension directory path)

The moz-extensions urls should resolve correctly in the main process (and I've also tried to load manually the source map URL related to the augury background page in a tab and it is loaded as expected) as well as in the content and extension processes, but a moz-extensions urls will fail to load in a "regular web page" context (e.g. an iframe embedded into a webpage) if it is not in the assets listed as "web_accessible_resources" in the extension manifest.

(The ExtensionProtocolHandler should never ends up into a nsResProtocolHandler, but during the extension is loading and while it is running, some requests to the "resource:" and "chrome:" protocols can be caught by the remote debugging server actors, but filtered to not be visible in the debugger panel when the devtools toolbox is running with an addon as its target, when the Firefox and/or WebExtensions internals are loaded and executed).

I'm going to dig more.

**Comment by rpl** [comment]
@clarkbw @tromey I've a theory: if in this "source map" mode the debugger is now loading the source maps from the extension url on the client side (in other words "it is fetching the source map data directly from the javascript running in the debugger ui panel") then, with the debugger panel running in the "browser toolbox process"and given that the related extension is not installed in the separate Firefox profile that the browser toolbox window is running on, the debugger panel would fail to load the source map from the extension url.

I also tried to load the background page in a tab and run the debugger panel from the tab developer toolbox and the webpack urls are listed, which suggest that the sourcemap file has been loaded correctly, and it seems to confirm this theory. 
(I've a patch that was initially part of Bug 1302702, but we agreed with Alex to defer it for a separate issue, which do not use the "browser toolbox process" for the "addon debugging window" when the extension is running in oop mode, I'm going to update that patch and check if my theory is correct and that change would fix this issue with the source map loading).

**Comment by rpl** [comment]
@clarkbw @tromey I've tested the above theory on a Nightly with the patches from ["Bug 1373219 - Use a regular toolbox for the Addon Debugger attached to a webextension in oop mode"](https://bugzilla.mozilla.org/show_bug.cgi?id=1373219) applied on top of a recent mozilla-central tip and it seems to confirm it: when the devtools toolbox is running in the same process (Firefox instance) where the extension is installed, the source maps seems to be loaded as expected.

**Comment by tromey** [comment]
Thanks for looking at this.  It sounds like we can close this in favor of that bug?

**Comment by clarkbw** [comment]
Yep! Thanks @rpl! I'll close this and track your bug from now on.
